services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile.yml
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.yml
    ports:
      - "8080:80"
    depends_on:
      - backend
